/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "jmcore"

pluginManagement {
  repositories {
    gradlePluginPortal()
    maven("https://repo.papermc.io/repository/maven-public/")
  }
}